name: unity setup

inputs:
  os:
    required:
  version:
    required:
  cachekey:
    required:
  UNITY_USERNAME:
    description: 'Required Unity account username.(With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository.)'
    required: true
  UNITY_PASSWORD:
    description: 'Required Unity account password.'
    required: true
  UNITY_SERIAL:
    description: 'Unity license serial key. Used for Plus/Professional license activation.'
    required: false
    default: ''
  UNITY_AUTHENTICATOR_KEY:
    description: 'Unity account authenticator key for Authenticator App (Two Factor Authentication). Used for account verification during Personal license activation.'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - uses: actions/cache/restore@v3
      id: cache-unity
      with:
        path: C:/UNITY
        key: ${{ inputs.os }}-${{ inputs.cachekey }}-unity 
    - name: MKDIR
      if: steps.cache-unity.outputs.cache-hit != 'true'
      shell: bash
      run: mkdir C:/UNITY
    - name: Setup Unity
      if: steps.cache-unity.outputs.cache-hit != 'true'
      uses: kuler90/setup-unity@v1
      with:
        unity-modules: windows-il2cpp
        unity-version: ${{ inputs.version }}
        install-path: C:/UNITY
    - uses: actions/cache/save@v3
      if: steps.cache-unity.outputs.cache-hit != 'true'
      with:
        path: C:/UNITY
        key: ${{ inputs.os }}-${{ inputs.cachekey }}-unity 

    - name: Activate Unity(by Serial)
      uses: kuler90/activate-unity@v1
      if: inputs.UNITY_SERIAL != null && inputs.UNITY_SERIAL != ''
      with:
        unity-path: C:/UNITY/${{ inputs.version }}/Editor/Unity.exe
        unity-username: ${{ inputs.UNITY_USERNAME }}
        unity-password: ${{ inputs.UNITY_PASSWORD }}
        unity-serial: ${{ inputs.UNITY_SERIAL }}
        
    - name: Activate Unity(by Authenticator)
      uses: kuler90/activate-unity@v1
      if: inputs.UNITY_AUTHENTICATOR_KEY != null && inputs.UNITY_AUTHENTICATOR_KEY != '' && (inputs.UNITY_SERIAL == null || inputs.UNITY_SERIAL == '')
      with:
        unity-path: C:/UNITY/${{ inputs.version }}/Editor/Unity.exe
        unity-username: ${{ inputs.UNITY_USERNAME }}
        unity-password: ${{ inputs.UNITY_PASSWORD }}
        unity-authenticator-key: ${{ inputs.UNITY_AUTHENTICATOR_KEY }}

    - name: Faliure
      if: (inputs.UNITY_AUTHENTICATOR_KEY == null || inputs.UNITY_AUTHENTICATOR_KEY == '') && (inputs.UNITY_SERIAL == null || inputs.UNITY_SERIAL == '')
      run: |
        echo "The UNITY_SERIAL or UNITY_AUTHENTICATOR_KEY  parameter is required."